name: Tests using qibolab main
on: push
jobs:
  tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install and configure poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Disable modern installer
        run: poetry config installer.modern-installation false
      - name: Install qibolab
        run: |
          git clone https://github.com/qiboteam/qibolab
          cd qibolab
          poetry install --no-interaction --no-root --with tests --all-extras
          cd ..
      - name: Test platforms
        run: |
          source $VENV
          export QIBOLAB_PLATFORMS=$(realpath .)
          pytest tests/
